feat: add ci final status (#30)

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -37,3 +37,19 @@ jobs:
     secrets:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  
+  final_status:
+    runs-on: ubuntu-latest
+    needs:
+      - website_ci
+      - infrastructure_ci
+    if: always()
+
+    steps:
+      - name: Validate pipeline result
+        run: |
+          if [[ "${{ needs.website_ci.result }}" == "failure" || \
+                "${{ needs.infrastructure_ci.result }}" == "failure" ]]; then
+            echo "CI failed"
+            exit 1
+          fi
